---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sdan-elasticsearch-cm
  labels:
    prj: sdan
    cnf: sdan-elasticsearch
data:
  elasticsearch.yml: |
    es.enforce.bootstrap.checks: true
    bootstrap.memory_lock: true
    xpack.monitoring.collection.enabled: false
    es_xpack_features: ["alerting","monitoring","graph","security"]
    xpack.ml.enabled: false

# More info:
# https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
