---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sdan-elasticsearch-cm
  labels:
    prj: sdan
    cnf: sdan-elasticsearch
data:
  elasticsearch.yml: |
    path:
      data: /var/lib/elasticsearch
      logs: /var/log/elasticsearch
    xpack.monitoring:
      enabled: false
      collection.enabled: false
    bootstrap.mlockall: true
    bootstrap.memory_lock: true
    xpack.security.enabled: false
    xpack.watcher.enabled: false
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    #es_xpack_features: ["alerting","monitoring","ml","graph","security"]
    es.enforce.bootstrap.checks: true
    discovery:
      type: "single-node"
      seed_hosts: []
      #seed_providers: 
      #initial_master_nodes: 
 
#  jvm.options: |
#    -Xms1g
#    -Xmx1g

# More info:
# https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
