---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdan-elasticsearch-deploy
  labels:
    prj: sdan
    cnf: sdan-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      prj: sdan
      cnf: sdan-elasticsearch
  template:
    metadata:
      labels:
        prj: sdan
        cnf: sdan-elasticsearch
    spec:
      #volumes:
      #- name: sdan-es-config-vol
      #  configMap:
      #    name: sdan-elasticsearch-cm
      containers:
      - name: elasticsearch
        image: elasticsearch:7.5.1
        imagePullPolicy: IfNotPresent
        resources: 
          requests: 
            memory: 2Gi
            cpu: 0.2
          limits: 
            memory: 4Gi
            cpu: 0.4
        #volumeMounts:
        #- name: sdan-es-config-vol
        #  mountPath: ./config
        #envFrom:
        #- configMapRef:
        #    name: sdan-elasticsearch-cm
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: discovery.type
          value: "single-node"
        - name: discovery.seed_hosts
          value: "[]"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        #- name: ES_MIN_MEM 
        #  value: 
        #- name: ES_MAX_MEM 
        #  value: 
        #- name: ES_TMPDIR
        #  value: "/tmp"
        #- name: bootstrap.memory_lock
        #  value: "true"
        ports:
        - containerPort: 9200 # for REST API
          protocol: TCP
        - containerPort: 9300 # for Nodes communication
          protocol: TCP
      #initContainers:
      #- name: init-sdan-elasticsearch-cm
      #  image: busybox
      #  command: ['sh','-c','sudo sysctl -w vm.max_map_count=262144']
      dnsPolicy: ClusterFirst # service.namespace.svc.cluster.local

