version: '3'
services:

  mongo:
    image: mongo
    networks:
      - graynet
    volumes:
      - mongo_data:/data/db
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://localhost:12201"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    deploy:
#      resources:
#        limits:
#          memory: 1g
    networks:
      - graynet
    volumes:
      - es_data:/usr/share/elasticsearch/data
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://localhost:12201"

  graylog:
    image: graylog/graylog:3.3.1
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://10.112.106.236:9000/
    networks:
      - graynet
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://localhost:12201"

  grafana:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
    networks:
      - graynet
    depends_on:
      - graylog
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://localhost:12201"

networks:
  graynet:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
  grafana_data:
    driver: local

