apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sdan-fluentd
  namespace: kube-system
  labels:
    name: sdan-fluentd-logging
spec:
  selector:
    matchLabels:
      name: sdan-fluentd-logging
  template:
    metadata:
      labels:
        name: sdan-fluentd-logging
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: sdan-fluentd
        image: sdan-fluentd
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
